name: greenvoice
description: A Speech-to-Text Converter designed specifically for hearing-impaired users.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  record: ^5.0.4
  path_provider: ^2.1.1
  http: ^1.1.0
  intl: ^0.18.1
  share_plus: ^7.2.1
  vibration: ^1.8.4
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
